version: 2
updates:
  - package-ecosystem: pip
    directory: /35_RUNTIME
    schedule:
      interval: monthly
  - package-ecosystem: docker
    directory: /35_RUNTIME
    schedule:
      interval: monthly
