from __future__ import annotations

HTML = r'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>AI DevOps Engineer — Operational Dashboard</title>
<style>
:root{color-scheme:dark;--bg:#08111f;--panel:#101c2f;--panel2:#0c1728;--border:#263752;--text:#e5edf7;--muted:#93a4ba;--accent:#67b7ff;--danger:#ff7d7d;--warn:#ffd37a;--ok:#69d19b}
*{box-sizing:border-box}body{font-family:Inter,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;margin:0;background:linear-gradient(180deg,#07111f,#0b1424 45%,#08111f);color:var(--text)}
main{max-width:1440px;margin:auto;padding:28px}.top{display:flex;justify-content:space-between;gap:18px;align-items:flex-start;flex-wrap:wrap}.eyebrow{font-size:12px;letter-spacing:.12em;text-transform:uppercase;color:var(--accent)}h1{margin:5px 0 6px;font-size:32px}.muted{color:var(--muted)}
.actions{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.btn{padding:10px 14px;border:1px solid var(--border);border-radius:9px;background:#14243b;color:var(--text);cursor:pointer}.btn:hover{border-color:#4d6b91}.btn.primary{background:#173b5b}.btn.danger{border-color:#694343}.pill{display:inline-block;padding:5px 9px;border-radius:999px;background:#17263c;border:1px solid var(--border);font-size:12px}.pill.high,.pill.critical{background:#3b2025;border-color:#704047;color:#ffd9dc}.pill.warning{background:#3f321b;border-color:#6e5c2c;color:#ffe9b1}.pill.ok{background:#17372a;border-color:#315e49;color:#bff5d9}.banner{margin:18px 0;padding:12px 14px;border:1px solid #5c3f3f;border-radius:10px;background:#26191d;color:#ffd9dc}
.stats{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:12px;margin:18px 0}.stat{background:var(--panel);border:1px solid var(--border);border-radius:12px;padding:16px}.stat .n{font-size:26px;font-weight:700}.stat .l{font-size:12px;color:var(--muted);margin-top:4px}
.layout{display:grid;grid-template-columns:1.15fr .85fr;gap:16px}.panel{background:rgba(16,28,47,.92);border:1px solid var(--border);border-radius:13px;padding:16px;min-width:0}.panel h2{font-size:17px;margin:0 0 12px}.toolbar{display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin-bottom:12px}.toolbar input,.toolbar select{background:#0a1525;color:var(--text);border:1px solid var(--border);border-radius:8px;padding:9px 10px}.list{display:flex;flex-direction:column;gap:9px;max-height:560px;overflow:auto}.row{background:var(--panel2);border:1px solid var(--border);border-radius:10px;padding:12px}.row.sel{border-color:#4f7ea9}.rowhead{display:flex;justify-content:space-between;gap:8px;align-items:flex-start}.row h3{font-size:14px;margin:0 0 5px}.meta{font-size:12px;color:var(--muted)}.summary{font-size:13px;line-height:1.45;margin:8px 0}.row .actions{margin-top:8px}
.detail{min-height:260px}.kv{display:grid;grid-template-columns:170px 1fr;gap:6px 12px;font-size:13px}.kv .k{color:var(--muted)}pre{white-space:pre-wrap;overflow:auto;background:#07101d;border:1px solid #1b2b42;border-radius:9px;padding:12px;font-size:12px}.section{margin-top:14px}.empty{padding:24px 10px;text-align:center;color:var(--muted)}.footer{margin-top:20px;color:var(--muted);font-size:11px;text-align:center}
@media(max-width:1050px){.stats{grid-template-columns:repeat(3,minmax(0,1fr))}.layout{grid-template-columns:1fr}}@media(max-width:650px){main{padding:16px}.stats{grid-template-columns:repeat(2,minmax(0,1fr))}.kv{grid-template-columns:1fr}.top h1{font-size:25px}}
</style></head>
<body><main>
<section class="top"><div><div class="eyebrow">AI DevOps Engineer</div><h1>Investigation & Operational Dashboard</h1><div class="muted">v3.14.0 — Community Local Runtime</div></div>
<div class="actions"><span id="runtime" class="pill">checking runtime…</span><button class="btn" onclick="refreshAll()">Refresh</button><button class="btn" onclick="seed()">Create demo incident</button><button class="btn" onclick="sendTelemetry()">Send demo telemetry</button></div></section>
<div class="banner"><b>Safety boundary:</b> investigations and connector observations are advisory/read-only. Production execution is disabled. The dashboard is not an authorization engine.</div>
<section id="stats" class="stats"></section>
<section class="layout">
<div class="panel"><h2>Incident Queue</h2><div class="toolbar"><input id="tenant" placeholder="Tenant filter (optional)" onkeydown="if(event.key==='Enter')refreshAll()"><select id="severity" onchange="renderIncidents(lastIncidents)"><option value="">All severities</option><option>critical</option><option>high</option><option>warning</option><option>info</option></select><span id="incidentCount" class="muted"></span></div><div id="incidents" class="list"></div></div>
<div class="panel detail"><h2>Incident / Investigation Detail</h2><div id="detail" class="empty">Select an incident or investigation.</div></div>
</section>
<section class="layout" style="margin-top:16px">
<div class="panel"><h2>Investigation Queue</h2><div id="investigations" class="list"></div></div>
<div class="panel"><h2>Recent Telemetry</h2><div id="telemetry" class="list"></div></div>
</section>
<div class="footer">AI DevOps Engineer v3.14.0 • evidence-first • human-in-the-loop • execution disabled</div>
</main>
<script>
let lastIncidents=[];let lastInvestigations=[];let timer=null;
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const pretty=x=>esc(JSON.stringify(x,null,2));
async function api(url,opts={}){const r=await fetch(url,opts);const j=await r.json();if(!r.ok)throw new Error(j.error_code||'request_failed');return j}
async function refreshAll(){try{const tenant=encodeURIComponent($('tenant').value.trim());const suffix=tenant?'?tenant_id='+tenant:'';const [p,s,i,v,t]=await Promise.all([api('/api/v1/product'),api('/api/v1/dashboard/summary'+suffix),api('/api/v1/incidents'+suffix),api('/api/v1/investigations?limit=50'+(tenant?'&tenant_id='+tenant:'')),api('/api/v1/telemetry/events?limit=12'+suffix)]);$('runtime').textContent='runtime ready';renderStats(s);lastIncidents=i.results||[];lastInvestigations=v.results||[];renderIncidents(lastIncidents);renderInvestigations(lastInvestigations);renderTelemetry(t.results||[])}catch(e){$('runtime').textContent='error: '+e.message}}
function renderStats(s){const totals=s.totals||{};const inc=s.incidents||{};const inv=s.investigations||{};$('stats').innerHTML=[['Incidents',totals.incidents??0],['Critical',inc.by_severity?.critical??0],['High',inc.by_severity?.high??0],['Investigations',totals.investigations??0],['Telemetry events',totals.telemetry_events??0]].map(x=>`<div class="stat"><div class="n">${esc(x[1])}</div><div class="l">${esc(x[0])}</div></div>`).join('')}
function renderIncidents(items){const filter=$('severity').value;const rows=(filter?items.filter(x=>x.severity===filter):items);$('incidentCount').textContent=`${rows.length} shown`;$('incidents').innerHTML=rows.length?rows.map(i=>`<div class="row"><div class="rowhead"><div><h3>${esc(i.incident_id)}</h3><div class="meta">${esc(i.tenant_id)} / ${esc(i.environment)} • state ${esc(i.state)}</div></div><span class="pill ${esc(i.severity)}">${esc(i.severity)}</span></div><div class="summary">${esc(i.candidate_reason||'No reason provided.')}</div><div class="meta">confidence ${(Number(i.confidence||0)*100).toFixed(0)}% • signals ${Array.isArray(i.signals)?i.signals.length:0}</div><div class="actions"><button class="btn" onclick="showIncident('${esc(i.incident_id)}')">Open</button><button class="btn primary" onclick="investigate('${esc(i.incident_id)}')">Investigate</button></div></div>`).join(''):'<div class="empty">No incidents match the current filter.</div>'}
function renderInvestigations(items){$('investigations').innerHTML=items.length?items.map(i=>`<div class="row"><div class="rowhead"><div><h3>${esc(i.investigation_id)}</h3><div class="meta">incident ${esc(i.incident_id)} • ${esc(i.environment)}</div></div><span class="pill ${i.status==='completed'?'ok':''}">${esc(i.status)}</span></div><div class="summary">mode: ${esc(i.mode)} • evidence ${Array.isArray(i.evidence)?i.evidence.length:0} • hypotheses ${Array.isArray(i.hypotheses)?i.hypotheses.length:0}</div><div class="actions"><button class="btn" onclick="showInvestigation('${esc(i.investigation_id)}')">Open investigation</button></div></div>`).join(''):'<div class="empty">No investigations yet. Investigate an incident to create one.</div>'}
function renderTelemetry(items){$('telemetry').innerHTML=items.length?items.map(t=>`<div class="row"><h3>${esc(t.component)} / ${esc(t.metric_family)}</h3><div class="meta">${esc(t.tenant_id)} / ${esc(t.environment)} • ${esc(t.condition)} • ${esc(t.severity_hint)}</div><div class="summary">value: ${esc(JSON.stringify(t.value))} • source: ${esc(t.source)}</div></div>`).join(''):'<div class="empty">No telemetry yet.</div>'}
async function showIncident(id){try{const i=await api('/api/v1/incidents/'+encodeURIComponent(id));$('detail').innerHTML=`<div class="kv"><div class="k">Incident</div><div>${esc(i.incident_id)}</div><div class="k">Tenant</div><div>${esc(i.tenant_id)}</div><div class="k">Environment</div><div>${esc(i.environment)}</div><div class="k">State</div><div>${esc(i.state)}</div><div class="k">Severity</div><div><span class="pill ${esc(i.severity)}">${esc(i.severity)}</span></div><div class="k">Confidence</div><div>${(Number(i.confidence||0)*100).toFixed(1)}%</div></div><div class="section"><b>Candidate reason</b><pre>${esc(i.candidate_reason||'')}</pre></div><div class="section"><b>Provenance</b><pre>${pretty(i.provenance||[])}</pre></div><div class="actions"><button class="btn primary" onclick="investigate('${esc(i.incident_id)}')">Start investigation</button></div>`}catch(e){alert(e.message)}}
async function showInvestigation(id){try{const i=await api('/api/v1/investigations/'+encodeURIComponent(id));$('detail').innerHTML=`<div class="kv"><div class="k">Investigation</div><div>${esc(i.investigation_id)}</div><div class="k">Incident</div><div>${esc(i.incident_id)}</div><div class="k">Status</div><div><span class="pill ${i.status==='completed'?'ok':''}">${esc(i.status)}</span></div><div class="k">Mode</div><div>${esc(i.mode)}</div><div class="k">Production execution</div><div>${i.safety?.production_execution_enabled?'ENABLED':'DISABLED'}</div></div><div class="section"><b>Evidence</b><pre>${pretty(i.evidence||[])}</pre></div><div class="section"><b>Hypotheses</b><pre>${pretty(i.hypotheses||[])}</pre></div><div class="section"><b>Unknowns</b><pre>${pretty(i.unknowns||[])}</pre></div><div class="section"><b>Requested diagnostics</b><pre>${pretty(i.requested_diagnostics||[])}</pre></div><div class="section"><b>Knowledge / RAG</b><pre>${pretty(i.knowledge||{})}</pre></div><div class="section"><b>Plan</b><pre>${pretty(i.plan||{})}</pre></div><div class="section"><b>Safety & provenance</b><pre>${pretty({safety:i.safety,provenance:i.provenance})}</pre></div>`}catch(e){alert(e.message)}}
async function seed(){try{await api('/api/v1/demo/seed',{method:'POST'});await refreshAll()}catch(e){alert(e.message)}}
async function sendTelemetry(){try{const base=Date.now()/1000,stamp=Date.now();const events=[{event_id:'ui-cpu-'+stamp,timestamp:base,tenant_id:'demo-tenant',environment:'lab',component:'node-01',metric_family:'cpu',condition:'high',severity_hint:'high',value:95,source:'ui-demo'},{event_id:'ui-memory-'+stamp,timestamp:base+10,tenant_id:'demo-tenant',environment:'lab',component:'node-01',metric_family:'memory',condition:'high',severity_hint:'high',value:92,source:'ui-demo'}];await api('/api/v1/telemetry/events',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({events})});await refreshAll()}catch(e){alert(e.message)}}
async function investigate(id){try{const j=await api('/api/v1/incidents/'+encodeURIComponent(id)+'/investigate',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({mode:'dry-run',include_connectors:true})});await refreshAll();await showInvestigation(j.investigation_id)}catch(e){alert('Investigation error: '+e.message)}}
refreshAll();
timer=setInterval(refreshAll,30000);
</script></body></html>'''
